name: paralvlympics
components:
  - name: app
    type: container
    image:
      repository: ghcr.io/alv-no/paralvlympics
      tag: sha-d961f0e
    config:
      expose:
        - port: 80
          type: http
      env:
        - name: 'PREFIX_SUPABASE_URL'
          value: 'https://jltydtjcwbpnbkixfekb.supabase.co/'
        - name: 'PREFIX_SUPABASE_PUBLISHABLE_KEY'
          value: 'sb_publishable_Nu6Qxges9LIW19cGaU08mA_Kf7UX8mU' #TODO move to a secret
